### ISSUE TITLE
Warning: vapor_rosnode validation failed: touched.ipv4: Path `touched.ipv4` is required.

### ISSUE THREAD

**Issue by HWiese1980** [roshub/vapor_master#28]
This is probably just a minor annoyance but I feel like feedback like this is appreciated, so...

I have a warning that frequently pops up during startup of some nodes. I cannot really pinpoint what's causing them but they appear to be reproducible. 

Here's the warning text: 

    (node:10869) UnhandledPromiseRejectionWarning: ValidationError: vapor_rosnode validation failed: touched.ipv4: Path `touched.ipv4` is required.
        at new ValidationError (/home/user/catkin_ws/src/vapor_master/node_modules/mongoose/lib/error/validation.js:27:11)
        at model.Document.invalidate (/home/user/catkin_ws/src/vapor_master/node_modules/mongoose/lib/document.js:1882:32)
        at p.doValidate.skipSchemaValidators (/home/user/catkin_ws/src/vapor_master/node_modules/mongoose/lib/document.js:1750:17)
        at /home/user/catkin_ws/src/vapor_master/node_modules/mongoose/lib/schematype.js:824:9
        at _combinedTickCallback (internal/process/next_tick.js:132:7)
        at process._tickCallback (internal/process/next_tick.js:181:9)
    (node:10869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)

**Comment by sevenbitbyte** [comment]
Hmm sounds like an IPv6 handling error of some sort. I've tried several IPv6 scenarios but can't seem to get this same error:

@HWiese1980 could you run with debugging turned on you can do that be prefixing `DEBUG=*` prior to your start command:

`DEUBG=* snap run vapor-master`

or if you're running from the npm package you can simply:

`yarn watch`

**Comment by NickZ** [comment]
@HWiese1980 This should have been fixed by #29, can you please test to see if it has?

**Comment by HWiese1980** [comment]
I'll test it sometime this week, thanks

**Comment by HWiese1980** [comment]
Oh, by the way, since `snap` has some major issues with unusual home paths (home directories in a different place than /home/user) on Ubuntu 16.04 I cannot use `snap`. I'm bound to stick to building from source.

**Comment by HWiese1980** [comment]
I've upgraded my local repository to commit 73478c3d4ca712cdb64dce292b69618b73825796 now. It seems like the warning **persists**, though. 

I'm seeing a bunch of new error messages now too. I guess though, it's probably better to open issues for them separately.
