### ISSUE TITLE
ValidationErrors but everything seems to work

### ISSUE THREAD

**Issue by rohbotics** [roshub/vapor_master#32]
Running from snap on Ubuntu Bionic.

Terminal 1: snap run vapor-master
Terminal 2: rosrun roscpp_tutorials talker
Terminal 3: rostopic echo /chatter

Everything seems to work, but the following errors are spewed out of vapor master.
```
ValidationError: vapor_paramSub validation failed: subscriberPath: Path `subscriberPath` is required., subscriberUri: Path `subscriberUri` is required., subscriberIpv4: Path `subscriberIpv4` is required.
    at new ValidationError (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/error/validation.js:27:11)
    at model.Document.invalidate (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/document.js:1882:32)
    at p.doValidate.skipSchemaValidators (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/document.js:1750:17)
    at /snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:824:9
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
error handling method call: 'subscribeParam': { ValidationError: vapor_paramSub validation failed: subscriberPath: Path `subscriberPath` is required., subscriberUri: Path `subscriberUri` is required., subscriberIpv4: Path `subscriberIpv4` is required.
    at ValidationError.inspect (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/error/validation.js:56:24)
    at formatValue (util.js:399:38)
    at inspect (util.js:293:10)
    at format (util.js:222:18)
    at Console.warn (console.js:145:21)
    at Object.master.onError (/snap/vapor-master/46/node_modules/vapor-master/src/master.js:39:11)
    at _callee$ (/snap/vapor-master/46/node_modules/vapor-master/node_modules/@roshub/express-xmlrpc/dist/index.js:159:27)
    at tryCatch (/snap/vapor-master/46/node_modules/vapor-master/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/snap/vapor-master/46/node_modules/vapor-master/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as throw] (/snap/vapor-master/46/node_modules/vapor-master/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/snap/vapor-master/46/node_modules/vapor-master/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _throw (/snap/vapor-master/46/node_modules/vapor-master/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:31:9)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  errors: 
   { subscriberPath: 
      { ValidatorError: Path `subscriberPath` is required.
    at new ValidatorError (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/error/validator.js:27:11)
    at validate (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:821:13)
    at /snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:870:11
    at Array.forEach (<anonymous>)
    at SchemaString.SchemaType.doValidate (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:830:19)
    at /snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/document.js:1748:9
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
        message: 'Path `subscriberPath` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'subscriberPath',
        value: undefined,
        reason: undefined,
        '$isValidatorError': true },
     subscriberUri: 
      { ValidatorError: Path `subscriberUri` is required.
    at new ValidatorError (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/error/validator.js:27:11)
    at validate (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:821:13)
    at /snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:870:11
    at Array.forEach (<anonymous>)
    at SchemaString.SchemaType.doValidate (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:830:19)
    at /snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/document.js:1748:9
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
        message: 'Path `subscriberUri` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'subscriberUri',
        value: undefined,
        reason: undefined,
        '$isValidatorError': true },
     subscriberIpv4: 
      { ValidatorError: Path `subscriberIpv4` is required.
    at new ValidatorError (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/error/validator.js:27:11)
    at validate (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:821:13)
    at /snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:870:11
    at Array.forEach (<anonymous>)
    at SchemaString.SchemaType.doValidate (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:830:19)
    at /snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/document.js:1748:9
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
        message: 'Path `subscriberIpv4` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'subscriberIpv4',
        value: undefined,
        reason: undefined,
        '$isValidatorError': true } },
  _message: 'vapor_paramSub validation failed',
  name: 'ValidationError' }
ValidationError: vapor_paramSub validation failed: subscriberPath: Path `subscriberPath` is required., subscriberUri: Path `subscriberUri` is required., subscriberIpv4: Path `subscriberIpv4` is required.
    at new ValidationError (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/error/validation.js:27:11)
    at model.Document.invalidate (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/document.js:1882:32)
    at p.doValidate.skipSchemaValidators (/snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/document.js:1750:17)
    at /snap/vapor-master/46/node_modules/vapor-master/node_modules/mongoose/lib/schematype.js:824:9
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by rohbotics** [comment]
Fixed with version 0.4.0
