### ISSUE TITLE
Error: searchParam not implemented

### ISSUE THREAD

**Issue by xdaco** [roshub/vapor_master#41]
I was trying vapor-master with one of our robot packages (originally developed on ros kinetic ) and got the following error. Our package is well tested and it works fine with ros kinetic ros_master. 
Any help/workaround will be appreciated !!

`Error: searchParam not implemented
    at Master.exports.searchParam (/snap/vapor-master/65/node_modules/vapor-master/src/param-api.js:119:9)
    at _callee$ (/snap/vapor-master/65/node_modules/vapor-master/node_modules/@roshub/express-xmlrpc/dist/index.js:147:32)
    at tryCatch (/snap/vapor-master/65/node_modules/vapor-master/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/snap/vapor-master/65/node_modules/vapor-master/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/snap/vapor-master/65/node_modules/vapor-master/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/snap/vapor-master/65/node_modules/vapor-master/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/snap/vapor-master/65/node_modules/vapor-master/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at /snap/vapor-master/65/node_modules/vapor-master/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/snap/vapor-master/65/node_modules/vapor-master/node_modules/core-js/library/modules/_export.js:36:28)
    at /snap/vapor-master/65/node_modules/vapor-master/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:23:12
    at /snap/vapor-master/65/node_modules/vapor-master/node_modules/@roshub/express-xmlrpc/dist/index.js:187:21
    at Layer.handle [as handle_request] (/snap/vapor-master/65/node_modules/vapor-master/node_modules/express/lib/router/layer.js:95:5)
    at next (/snap/vapor-master/65/node_modules/vapor-master/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/snap/vapor-master/65/node_modules/vapor-master/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/snap/vapor-master/65/node_modules/vapor-master/node_modules/express/lib/router/layer.js:95:5)
`

**Comment by sevenbitbyte** [comment]
@NickZ What is the level-of-effort to finish the `param-api`.`searchParam`?

https://github.com/roshub/vapor_master/blob/658d8a624b2ab07f1d91f9b7ba196e5bdca49f29/src/param-api.js#L112-L120

**Comment by NickZ** [comment]
This shouldn't be a huge amount of effort, this would be a simple mongodb query in the params table and then sorting by path to find the first partial match in the namespace.

[RosMaster SearchParam api listing](https://docs.ros.org/kinetic/api/rosmaster/html/rosmaster.master_api.ROSMasterHandler-class.html#searchParam)
[Mongoose](https://mongoosejs.com/docs/api.html#model_Model.find)

**Comment by sevenbitbyte** [comment]
@NickZ how'd we miss this in matching ROS Test results for rosmaster?
